language: python

dist: xenial

python:
  - "3.8"
  - "3.9"

install:
  - pip install .[test]

script:
  - coverage run -m unittest tests --quiet
  - coverage report --show-missing
  - codecov

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "THQ6KeKJF2SUoxyrb7kiDk6wMVtzSKw3B7XN9t16z2IIb+iHLoDTNU6A50ppe4HOY6B/oa3ri1IuOYBIbLqP59IS6P44bAwOVydctYxXpIHm2PG7rG2hG3i88K+9FOI8+ZauBuN67RkVMBgVOgvOk1nhhCGuinOOxDK0cDuEDGqdazPEAXOBL32cY1SQzVeMragqP0TPTQKRov//2B5LS610J3r/ZP2Pqy9esQaUJ437j3cpk81uqGCU60rsG5bn9hpehcPuIYAOs4N7FquYS7P2v++B/d5uAlrmsu0I7y7hg6gXP0TwfLlV8nG7wjuOgxOlkcRlUstFwCzhjTfMfYphyCTBq0/e2f/XGtQ23D2dyI9Ny+46lr+iFk3D6jnI+iFnwz9C23mfzx/rL931IQysoj3aJeDlFxINie2JjoEzrJe8YvqlgxGUECU3G2pCjPdUHbp5QI7RKFljyOvPcXuWwWFVkWlObIHVXZQ3g2T2f9hHdfSpqSUxtzwamCFkNZg89+2k7m+9fXEuKD4io8Sxih95q2R5mXfW3OCS2IN011Yp1L3T4dH/MR8nHFQ88ySru12neERuBWcaGPZ+CmEyiISqlAvq3xXZ/dRbjows/Y00Z7VRbqr+oNyjD4fGKf3VfydiQJGKuGJ/JmnCF4XeVX9swHAm1efTt1W4pow="
  skip_existing: true
  on:
    tags: true
